# Generated by Django 5.1.3 on 2024-12-02 09:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('land', 'Land')], max_length=10)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('house_number', models.CharField(blank=True, max_length=10, null=True)),
                ('apartment_number', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('commission_share', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.property')),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Apartment',
                'verbose_name_plural': 'Apartments',
            },
            bases=('api.property',),
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.property')),
                ('floors', models.IntegerField(blank=True, null=True)),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'House',
                'verbose_name_plural': 'Houses',
            },
            bases=('api.property',),
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.property')),
                ('area', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Land',
                'verbose_name_plural': 'Lands',
            },
            bases=('api.property',),
        ),
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('land', 'Land')], max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('min_price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('max_price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('min_area', models.FloatField(blank=True, null=True)),
                ('max_area', models.FloatField(blank=True, null=True)),
                ('min_rooms', models.IntegerField(blank=True, null=True)),
                ('max_rooms', models.IntegerField(blank=True, null=True)),
                ('min_floor', models.IntegerField(blank=True, null=True)),
                ('max_floor', models.IntegerField(blank=True, null=True)),
                ('min_floors', models.IntegerField(blank=True, null=True)),
                ('max_floors', models.IntegerField(blank=True, null=True)),
                ('min_land_area', models.FloatField(blank=True, null=True)),
                ('max_land_area', models.FloatField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_needs', to='api.client')),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtor_needs', to='api.realtor')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_offers', to='api.client')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.property')),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtor_offers', to='api.realtor')),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.need')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.offer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('need', 'offer'), name='unique_deal')],
            },
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='offer_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='need',
            constraint=models.CheckConstraint(condition=models.Q(('min_price__gt', 0)), name='need_min_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='need',
            constraint=models.CheckConstraint(condition=models.Q(('max_price__gt', 0)), name='need_max_price_positive'),
        ),
    ]
