# Generated by Django 5.1.3 on 2024-12-04 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='areal',
            new_name='area',
        ),
    ]
