# Generated by Django 5.1.3 on 2024-12-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_areal_property_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='need',
            name='property_type',
            field=models.CharField(choices=[('Квартира', 'Квартира'), ('Дом', 'Дом'), ('Земля', 'Земля')], max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Квартира', 'Квартира'), ('Дом', 'Дом'), ('Земля', 'Земля')], max_length=10),
        ),
    ]
