# Generated by Django 5.1.3 on 2024-12-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_need_property_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='need',
            name='address',
        ),
        migrations.AddField(
            model_name='need',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='need',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='need',
            name='house_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='need',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
