# Generated by Django 5.1.3 on 2024-12-12 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_need_address_need_apartment_number_need_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='need',
            name='max_land_area',
        ),
        migrations.RemoveField(
            model_name='need',
            name='min_land_area',
        ),
    ]
