# Generated by Django 5.1.3 on 2024-12-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_need_max_land_area_remove_need_min_land_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время события')),
                ('duration', models.DurationField(verbose_name='Длительность события')),
                ('event_type', models.CharField(choices=[('meeting', 'Встреча с клиентом'), ('showing', 'Показ'), ('call', 'Запланированный звонок')], max_length=10, verbose_name='Тип события')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'ordering': ['date_time'],
            },
        ),
    ]
