# Generated by Django 5.1.3 on 2024-12-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_act_delete_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='act_type',
            field=models.CharField(choices=[('Встреча с клиентом', 'Встреча с клиентом'), ('Показ', 'Показ'), ('Запланированный звонок', 'Запланированный звонок')], max_length=25, verbose_name='Тип события'),
        ),
    ]
