# Generated by Django 5.1.3 on 2024-12-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_property_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='images',
        ),
        migrations.AddField(
            model_name='property',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='property_photo/', verbose_name='Фотографии'),
        ),
    ]
